p_value: 0.5
k_count: 10
max_bound: 50
min_bound: 0

crb_tag: 'crb20_fea66'

dataset:
  label_directory: 'labels' #'scribbles'
  root_dir: 'data/sequences'
  prefix: baseline
  aug: []
  sampling:
    strategy: full
    beta: 0